---
- name: Test
  hosts: guinea_pigs
  gather_facts: true
  become: true
  tasks:
    - name: Install and uninstall service
      block:
      - include_role:
          name: '/home/jon/Code/ansible-nebula'

      - name: Disable nebula service
        systemd:
          name: nebula
          state: stopped
          enabled: false

      - name: Delete nebula directory and services
        file:
          path: "{{ item }}"
          state: absent
        with_items:
        - "{{ nebula_certificate_dir }}"
        - "{{ nebula_config_dir }}"
        - "{{ nebula_bin_dir }}/nebula"
        - "{{ nebula_bin_dir }}/nebula-cert"
        - "/etc/systemd/system/nebula.service"
      become: true
    